// Dev-time generator for emoji/data.js. NOT shipped to users' machines at runtime and the
// extension never imports it. Usage:
//   npm install emojibase-data && node tools/gen-emoji.mjs ./node_modules/emojibase-data > emoji/data.js
// The output is a plain JS module with two exports (GROUPS, DATA); the extension has no
// dependency on emojibase or any other package.
import {readFileSync} from 'node:fs';
import {join} from 'node:path';

const dir = process.argv[2] ?? './node_modules/emojibase-data';
const read = f => JSON.parse(readFileSync(join(dir, 'en', f), 'utf8'));
const emojis = read('compact.json');
const messages = read('messages.json');
const github = read('shortcodes/github.json');
const version = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')).version;

// group 2 is the "components" bucket (skin tones, hair); entries without a group are
// regional-indicator letters. Neither is useful as a pickable emoji.
const groups = messages.groups.filter(g => g.key !== 'component').sort((a, b) => a.order - b.order);
const groupIndex = new Map(groups.map((g, i) => [g.order, i]));

const clean = s => String(s).replace(/[\t\n\r\\`]|\$\{/g, ' ').trim();
const lines = [];
for (const e of [...emojis].sort((a, b) => a.order - b.order)) {
    if (e.group === undefined || !groupIndex.has(e.group))
        continue;
    const sc = github[e.hexcode];
    const codes = Array.isArray(sc) ? sc : sc ? [sc] : [];
    const words = new Set([...(e.tags ?? []), ...codes].map(w => clean(w).toLowerCase()).filter(Boolean));
    // line: emoji TAB label TAB space-separated keywords TAB group index
    lines.push([e.unicode, clean(e.label), [...words].join(' '), groupIndex.get(e.group)].join('\t'));
}

process.stdout.write(`// GENERATED by tools/gen-emoji.mjs from emojibase-data ${version} (MIT). Do not edit by hand.
// Plain data only: parsed lazily by emoji/emoji.js the first time the picker is used.
export const GROUPS = ${JSON.stringify(groups.map(g => g.message))};

export const DATA = \`${lines.join('\n')}\`;
`);
